"""empty message

Revision ID: e364c4624699
Revises: f51b69dc5275
Create Date: 2018-09-17 20:30:49.928342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e364c4624699'
down_revision = 'f51b69dc5275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=True))
    op.drop_column('user', 'pw_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pw_hash', sa.VARCHAR(length=80), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
